version: "3.9"

services:
  # Springboot backend service
  backend:
    image: maven:3.9.12
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ./mvnw spring-boot:run
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      IP_ADDRESS: mariadb
      DB_USER: appuser
      DB_PASSWORD: apppassword
    ports:
      - "8080:8080"

  # Mariadb database
  mariadb:
    image: mariadb:12
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: camerashopdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Adminer database client
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8081:8080"

volumes:
  mariadb_data:
