spring:
  application:
    name: camerashopapi

  datasource:
    url: jdbc:mariadb://192.168.1.177:3306/camerashopdb
    username: samael
    password: StrongPass1!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: never
